spring:
  application:
    name: ms-ticket-manager
  data:
    mongodb:
      uri: mongodb+srv://${USERNAME}:${DB_PASSWORD}@clusterdesafio3.mpnjzen.mongodb.net/db-ticket?retryWrites=true&w=majority&appName=ClusterDesafio3
