spring:
  application:
    name: ms-ticket-manager
  data:
    mongodb:
      uri: ${MONGO_URL}

security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: ${JWT_EXPIRATION_LENGTH}

feign:
  event-manager:
    name: ms-event-manager
    url: ${EVENT_MANAGER_URL}

springdoc:
  paths-to-match:
    - /api/v1/**
    - /auth/**