spring:
  application:
    name: ms-event-manager
  data:
    mongodb:
      uri: ${MONGO_URL}

  cloud:
    openfeign:
      okhttp:
        enabled: true

feign:
  data-resource:
    name: via-cep
    url: ${VIA_CEP_URL}
  ticket-manager:
    name: ms-ticket-manager
    url: ${TICKET_MANAGER_URL}

server:
  port: 8081