spring:
  application:
    name: ms-event-manager
  data:
    mongodb:
      uri: mongodb+srv://${USERNAME}:${DB_PASSWORD}@clusterdesafio3.mpnjzen.mongodb.net/db-event?retryWrites=true&w=majority&appName=ClusterDesafio3
feign:
  data-resource:
    name: via-cep
    url: https://viacep.com.br/ws
  ticket-manager:
    name: ms-ticket-manager
    url: http://localhost:8080/api/v1

server:
  port: 8081